### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by xxxmonsterxxx** [xxxmonsterxxx/SGR#2]
**ROADMAP**
- [x] Add engine version
- [x] Realize possibility to change version of app
- [x] Check in the code enum warnings
- [ ] Make init order list
- [x] Add picked phys device to device manager instead same in base class SGR
- [x] Rename custom types using big first letter
- [x] Add choice of all compatible devices
- [ ] Realize multithreading for dont stop drawing while resizing or window moving
- [x] Пофиксить билд SGR, а именно аргумент симейка для того чтобы можно было не фиксить файл а из командной строки указать релиз или дебаг
- [x] При сборке копирование всех ресурсов ОБЯЗАТЕЛЬНО в папку сборки!!!
- [x] Проверить требуется ли для создания меша цвет. Достаточно ли оставить только в объекте
- [x] Пофиксить версию в исходниках
- [x] Чуть пофиксить скрипт формирования релиза, SGR-vX.X.X/vX.X.X/
- [x] Добавить версионность движка
- [x] Реализовать изменение версионности и названия приложения в SGR.h
- [x] Разобраться с ворнингами по энаму
- [x] При ините написать зависимости инициализации (что должно быть иинициализировано для чего)
- [x] Добавить пикед физ девайс в деввайс мэнэджер и избавиться от этой же переменной в сгр
- [x] Поменять sgrPhysDev... на SgrPhysDev имена типов должны быть с большой буквы
- [x] Добавить поддержку поиска ВСЕХ подходящих физических устройств, предоставление списка, выбор устройства должен быть только для подходящих.
- [x] Разобраться с очередями, возможно сделать не две конкретных а список уникальных доступных и их количество.
- [x] Заменить префиксы всех локальных полей классов без приставки о названии класса например windowWidth на width.
- [x] У SurfaceManager переименовать capabilities чтобы избежать тавтологии capabilities.capabilities
- [ ] Погуглить существования макроса на создание шаблона синглтона
- [ ] Убрать класс френды или подумать о том надо ли они.
- [ ] Попробовать создать второй поток для обработки колбэков окна.
- [x] При реините команд мэнэджера добавить деструктор вектора команд, которые делают execute.
- [x] Переименовать инит функции всех мэнэджеров просто на "init()"
- [x] Разобраться надо ли передавать в пайплайн лэйаут все дескриптор лейэауты или только один
- [x] Добавить возможность создания кастомного юниформ объекта
- [x] При добавлении кастомного лэйаут дескриптора сделать реинит пайплайна -> свопчейна
- [x] Добавить очистку staging buffer
- [ ] Проверить надо ли чтобы в структуре физ девайс были фиксед графикс и пресент куи
- [x] Переименовать поле grPhysicalDevice.physDevice на vkPhysDevice
- [ ] Избавиться от ненужных ссылок или указателей в аргументах функций, то есть чтобы передавать не указатели а сами объекты
- [x] Добавить возможность добавления кастомных дескриптор сетов, кастомного дескриптор лэйаута и тд.
- [x] Пересмотреть название всех объектов в т.ч. SgrDynamicUniformBufferObject слишком длинные
- [x] Изменить аргументы для функции обновления динамического юнифором буфера второй аргумент сделать только указатель на все объекты void*
- [x] Написать гайд также по прикручиваю движков к проекту, а не только по сборке.
- [x] переделать смейк, чтобы не создавал билд
- [x] добавить в смейк опцию очистки и полной пересборки
- [x] реализовать автосборку экзэмпла и копирование бинарника с ресурсами внутрь релиза
- [x] VK_CHECK_RESULT - реализовать
- [x] при добавлении addInstanceObject - реализовать проверку на уникальность имени
- [x] Проверить можно ли избавиться от dynamic alignments аргумента при вызове функции AddObjectInstance
- [x] разобраться с динамик алайнментом (должен ли он быть собственный для каждой геометрии либо общий на все геометрии)
- [x] исправить размер текстуры (приходится вводить умноженное на два)
- [ ] проверить поддерживает ли код рил тайм добавление объекта для рисования
- [x] проверить можно ли избавиться от "empty" объектов в векторах
- [x] написать скрипт для генерации всех шейдоров в папке в другую папку
- [x] начинает подлагивать во время перемещения окошка
- [x] Добавить поддержку слоёв валидации
- [x] Сделать более структурированные и понятные симейк скрипты
- [ ] Разобраться с MAKE_API_VERSION что такое вариант
- [x] Реализовать ПРОВЕРКУ требуемых экстеншенсов
- [x] Подумать над тем, надо ли чтоб CreateImage  in SwapChainManager был статичным
- [x] Рассмотреть ситуацию когда слои валидации могли быть недоступны, но работу движка продолжаем
- [x] Разобраться со слоями валидации от сторонних разработчиков (Почему они автоматичеки загружаются к моей программе)
- [x] Провести анализ профилировщиком инструментом
- [x] Провести анализ на проблемы с памятью инструментом
- [x] добавить чекер операции чтобы избавиться от рез = функция иф рез не равно ок то ретёрн рез
- [ ] заменить стринговые идентификаторы на хэш таблицы
- [ ] createDynamicUniformBuffer добавить эту функцию с одним аргументов, а остальная инфа чтобы из него бралась
- [ ] узнать можно ли в спирв шейдерах использовать уникальную биндинг номер для разных стейджев то есть не сквозную
- [ ] по идее можно создавать один дескриптор пул и в нём указаывать вектор размеров а не для каждого набора дескрипторов создавать пул дескрипторов
- [ ] от глобал убо надо отказаться, так как по факту это инстанс убо, только меняется одновременно для всех, а по сути такая же часть данных для каждого инстанса. идея - инстанс дата добавить поле глобал вью локал и т.д....
- [ ] избавить от дубликатов шейдеров и пайплайнов/рендерпасов т.к. при одинаковых настройках для каждой геометрии создаётся свой уникальный. это излишне
- [ ] Доработать линукс экземпл апп, не копируется симлинк фоллов чейн, не копируется .десктоп файл
- [ ] после установки через скрипт на линуксе надо ещё сделать сорс башрс иначе сразу не видит пути к либам при сборке сге
